name: Unit tests

on: [push]

jobs:
  unit-tests-api:
    name: Run API unit tests
    runs-on:
      - ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: API unit tests
        run: npm run test:unit
